config/routes.rb
Rails.application.routes.draw do
  root 'schedules#show'
  # get "/" => "schedules#index"
  get "schedules/kiyaku" => "schedules#kiyaku"
  resources :answers
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :schedule
    validates :name, presence: true

    #Answer.where(reason: "sanka")
    scope :sanka, -> { where(reason: "sanka")}
    scope :tabun, -> { where(reason: "tabun")}
    scope :mitei, -> { where(reason: "mitei")}
    scope :kesseki, -> { where(reason: "kesseki")}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    has_many :answers, dependent: :destroy
    validates :place, presence: true
    validates :addcomment, presence: true

    scope :uketsukechu, -> { where("schedules.ymd > ?", Time.current.yesterday) }
    # default_scope -> { order(ymd: :asc) }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    redirect_to '/schedules'
    @answers = Answer.all

  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
    @answers = Answer.all
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        #format.html { redirect_to schedules_url, notice: '出欠を登録しました。' }
        format.html { redirect_to :action=>"show", :controller=>"schedules", :id=>@answer.schedule_id, notice: '出欠を登録しました。' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { redirect_to schedules_url, notice: '名前が記入されていません。' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: '出欠を更新しました。' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to :action=>"show", :controller=>"schedules", :id=>@answer.schedule_id, notice: '登録が削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:schedule_id, :name, :reason, :comment)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    
    #@schedules = Schedule.all
    #@schedules = Schedule.where("schedules.ymd > ?", Time.current.yesterday).reorder(:ymd)
    @schedules = Schedule.where("schedules.ymd > ?", Time.current.yesterday).reorder(:ymd)
    @workschedule =@schedules.first
    
    if @workschedule.present?
      @answers_sanka = @workschedule.answers.where("reason =?",'sanka')
      @answers_tabun = @workschedule.answers.where("reason =?",'tabun')
      @answers_mitei = @workschedule.answers.where("reason =?",'mitei')
      @answers_kesseki =  @workschedule.answers.where("reason =?",'kesseki')
    end

    #@answers = Answer.all
    #@answers_sanka = Answer.sanka
    #@answers_tabun = Answer.tabun
    #@answers_mitei = Answer.mitei
    #@answers_kesseki = Answer.kesseki
    @answer = Answer.new
    @answer.schedule_id = params[:id]

    @caution = '※チーム毎でサイト管理している為、パスワードを設けておりません。チーム幹事のみ編集してください。'
    
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedules = Schedule.where("schedules.ymd > ?", Time.current.yesterday).reorder(:ymd)
    @workschedule =@schedules.first
    
    if @workschedule.present?
      @answers_sanka = @workschedule.answers.where("reason =?",'sanka')
      @answers_tabun = @workschedule.answers.where("reason =?",'tabun')
      @answers_mitei = @workschedule.answers.where("reason =?",'mitei')
      @answers_kesseki =  @workschedule.answers.where("reason =?",'kesseki')
    end

    #@answers = Answer.all
    #@answers_sanka = Answer.sanka
    #@answers_tabun = Answer.tabun
    #@answers_mitei = Answer.mitei
    #@answers_kesseki = Answer.kesseki
    if@workschedule.present?
      if params[:id]
        schedule = Schedule.find(params[:id])
        @answers_sanka =  schedule.answers.where("reason =?",'sanka')
        @answers_tabun =  schedule.answers.where("reason =?",'tabun')
        @answers_mitei =  schedule.answers.where("reason =?",'mitei')
        @answers_kesseki =  schedule.answers.where("reason =?",'kesseki')
      else
        schedule = Schedule.uketsukechu.order(ymd: :asc).first
        @answers_sanka =  schedule.answers.where("reason =?",'sanka')
        @answers_tabun =  schedule.answers.where("reason =?",'tabun')
        @answers_mitei =  schedule.answers.where("reason =?",'mitei')
        @answers_kesseki =  schedule.answers.where("reason =?",'kesseki')
      end
    end

    #@answers_all = schedule.answer
    #@answers_sanka = schedule.answer.sanka
    #@answers_tabun = schedule.answer.tabun
    #@answers_mitei = schedule.answer.mitei
    #@answers_kesseki = schedule.answer.kesseki

    @answer = Answer.new
    @answer.schedule_id = params[:id]

    @caution = '※チーム毎でサイト管理している為、パスワードを設けておりません。チーム幹事のみ編集してください。'
  end

  # GET /schedules/kiyaku
  def kiyaku
  end
  
  # GET /schedules/new
  def new
    @schedules = Schedule.where("schedules.ymd > ?", Time.current.yesterday).reorder(:ymd)
    @schedules = Schedule.all
    @schedule = Schedule.new
    @schedules = Schedule.all.order(ymd: "ASC")

    if @schedules.present?
      @kizonschedule = Schedule.where("schedules.ymd > ?", Time.current.yesterday).reorder(:ymd).first
    else
      @kizonschedule = 0
    end
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to new_schedule_path, notice: 'スケジュールが作成されました。' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { redirect_to new_schedule_path, notice: '開催場所、もしくは詳細が記載されていません。' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to new_schedule_path, notice: 'スケジュールが更新されました。' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to new_schedule_path, notice: 'スケジュールが削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = if params[:id].blank?
        #Schedule.uketsukechu.first
        Schedule.where("schedules.ymd > ?", Time.current.yesterday).reorder(:ymd).first
      else
        Schedule.find(params[:id])
      end
      # @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:ymd, :start, :end, :place, :addcomment)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :schedule_id %>
    <%= form.number_field :schedule_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Schedule</th>
      <th>Name</th>
      <th>Reason</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.schedule_id %></td>
        <td><%= answer.name %></td>
        <td><%= answer.reason %></td>
        <td><%= answer.comment %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<table cellspacing="0" cellpadding="0">
<tr>
    <th class="border_n" align="center" bgcolor="#e0e0e0">スケジュールID</th>
    <th class="border_l" align="center" bgcolor="#e0e0e0">名前</th>
    <th class="border_l" align="center" bgcolor="#e0e0e0">出欠</th>
    <th class="border_l" align="center" bgcolor="#e0e0e0">コメント</th>
</tr>
<tr>
  <td class="border_t"><%= @answer.schedule_id %></td>
  <td class="border_tl"><%= @answer.name %></td>
  <td class="border_tl"><%= @answer.reason %></td>
  <td class="border_tl"><%= @answer.comment %></td>
</tr>
</table>

<%= link_to '編集する', edit_answer_path(@answer) %> |
<%= link_to '戻る', answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
       <title>Soleo Platini</title>
<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header><h1>Soleo Platini</h1></header>
    <div id="column"><%= yield %></div>
  <footer>&copy;2022 D Brand Co.,Ltd.<span><%= link_to 'ご利用規約', schedule_path('kiyaku'), { class: "tar" } %></span></footer>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <table cellspacing="0" cellpadding="0">
    <tr>
        <th class="border_n" align="center" bgcolor="#e0e0e0">開催日時</th>
        <th class="border_l" align="center" bgcolor="#e0e0e0">開始時間</th>
        <th class="border_l" align="center" bgcolor="#e0e0e0">終了時間</th>
        <th class="border_l" align="center" bgcolor="#e0e0e0">開催場所</th>
        <th class="border_l" align="center" bgcolor="#e0e0e0">詳細</th>
        <th colspan="3" class="border_l" align="center" bgcolor="#e0e0e0">アクション</th>
    </tr>
    <tr>
      <td class="border_t" align="center"><%= form.date_select :ymd, { class: "btn-border" } %></td>
      <td class="border_tl" align="center"><%= form.time_select :start, {default: Date.today + 9.hour} %></td>
      <td class="border_tl" align="center"><%= form.time_select :end, {default: Date.today + 13.hour} %></td>
      <td class="border_tl" align="center"><%= form.text_field :place %></td>
      <td class="border_tl" align="center"><%= form.text_area :addcomment %></td>
      <td class="border_tl" align="center"><%= form.submit %></td>
    </tr>
</table>

<% end %>

app/views/schedules/edit.html.erb
<h1>イベントを編集する</h1>

<%= render 'form', schedule: @schedule %>

<div style="clear: both; padding-top: 20px;"><%= link_to '編集画面に戻る', new_schedule_path, { class: "btn-border" } %></div>

app/views/schedules/kiyaku.html.erb
<div style="clear: both; padding-top: 10px; margin-bottom: 30px;"><%= link_to '日程一覧に戻る', schedules_path, { class: "btn-border" } %></div>

<h1>利用規約</h1>
<p>この利用規約（以下，「本規約」といいます。）は，株式会社D Brand（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

<h2>第1条（適用）</h2>
<ol>
    <li>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
    <li>当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
    <li>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
</ol>

<h2>第2条（利用登録）</h2>
<ol>
    <li>本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこの承認を登録希望者に通知することによって，利用登録が完了するものとします。</li>
    <li>当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</li>
    <ol>
        <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
        <li>本規約に違反したことがある者からの申請である場合</li>
        <li>その他，当社が利用登録を相当でないと判断した場合</li>
    </ol>
</ol>

<h2>第3条（ユーザーIDおよびパスワードの管理）</h2>
<ol>
    <li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
    <li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
    <li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</li>
</ol>

<h2>第4条（利用料金および支払方法）</h2>
<ol>
    <li>ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</li>
    <li>ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</li>
</ol>

<h2>第5条（禁止事項）</h2>
<p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
<ol>
    <li>法令または公序良俗に違反する行為</li>
    <li>犯罪行為に関連する行為</li>
    <li>当社，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
    <li>当社のサービスの運営を妨害するおそれのある行為</li>
    <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
    <li>不正アクセスをし，またはこれを試みる行為</li>
    <li>他のユーザーに成りすます行為</li>
    <li>当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
    <li>当社，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
    <li>以下の表現を含み，または含むと当社が判断する内容を本サービス上に投稿し，または送信する行為</li>
    <ol>
        <li>過度に暴力的な表現</li>
        <li>露骨な性的表現</li>
        <li>人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</li>
        <li>自殺，自傷行為，薬物乱用を誘引または助長する表現</li>
        <li>その他反社会的な内容を含み他人に不快感を与える表現</li>
    </ol>
    <li>以下を目的とし，または目的とすると当社が判断する行為</li>
    <ol>
        <li>営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。）</li>
        <li>性行為やわいせつな行為を目的とする行為</li>
        <li>面識のない異性との出会いや交際を目的とする行為</li>
        <li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
        <li>当社，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</li>
        <li>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
    </ol>
    <li>宗教活動または宗教団体への勧誘行為</li>
    <li>その他，当社が不適切と判断する行為</li>
</ol>

<h2>第6条（本サービスの提供の停止等）</h2>
<ol>
    <li>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
    <ol>
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他，当社が本サービスの提供が困難と判断した場合</li>
    </ol>
    <li>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
</ol>

<h2>第7条（著作権）</h2>
<ol>
    <li>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。</li>
    <li>ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当社は，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。</li>
    <li>前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</li>
</ol>

<h2>第8条（利用制限および登録抹消）</h2>
<ol>
    <li>当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。</li>
    <ol>
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>登録事項に虚偽の事実があることが判明した場合</li>
        <li>決済手段として当該ユーザーが届け出たクレジットカードが利用停止となった場合</li>
        <li>料金等の支払債務の不履行があった場合</li>
        <li>当社からの連絡に対し，一定期間返答がない場合</li>
        <li>本サービスについて，最終の利用から一定期間利用がない場合</li>
        <li>その他，当社が本サービスの利用を適当でないと判断した場合</li>
    </ol>
    <li>前項各号のいずれかに該当した場合，ユーザーは，当然に当社に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</li>
    <li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
</ol>

<h2>第9条（退会）</h2>
<p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>

<h2>第10条（保証の否認および免責事項）</h2>
<ol>
    <li>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
    <li>当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
    <li>前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
    <li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
</ol>

<h2>第11条（サービス内容の変更等）</h2>
<p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>

<h2>第12条（利用規約の変更）</h2>
<p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。</p>

<h2>第13条（個人情報の取扱い）</h2>
<p>当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。</p>

<h2>第14条（通知または連絡）</h2>
<p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>

<h2>第15条（権利義務の譲渡の禁止）</h2>
<p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>

<h2>第16条（準拠法・裁判管轄）</h2>
<ol>
    <li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
    <li>弊社と利用者の本サービスの利用に関する一切の紛争（裁判所の調停手続きを含む）は、弊社の本社所在地を管轄する簡易裁判所または地方裁判所を第一審の専属的合意管轄裁判所とすることに合意する。</li>
</ol>

<div style="clear: both; padding-top: 10px;"><%= link_to '日程一覧に戻る', schedules_path, { class: "btn-border" } %></div>

app/views/schedules/new.html.erb
<p id="notice"><%= notice %></p>

<h1>イベント一覧</h1>

<table cellspacing="0" cellpadding="0">
    <tr>
        <th class="border_n" align="center" bgcolor="#e0e0e0">開催日時・場所</th>
        <th class="border_l" align="center" bgcolor="#e0e0e0">コメント</th>
        <th colspan="2" class="border_l" align="center" bgcolor="#e0e0e0">アクション</th>
    </tr>
    <% @schedules.each do |schedule| %>
    <tr>
        <td class="border_t">
            <% weeks = ["月","火","水","木","金","土","日"] %>
            <% index = schedule.ymd.strftime("%u").to_i %>
            <%= schedule.ymd.strftime("%Y年%m月%d日(#{weeks[index - 1]})") %><br><%= schedule.start.strftime('%H:%M') %> ～ <%= schedule.end.strftime('%H:%M') %><br><%= schedule.place %>
        </td>
        <td class="border_tl"><%= simple_format schedule.addcomment %></td>
        <td class="border_tl" align="center"><%= link_to '編集', edit_schedule_path(schedule), { class: "btn-border" } %></td>
        <td class="border_tl" align="center"><%= link_to '削除', schedule, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: "btn-border" %></td>
    </tr>
    <% end %>
</table>

<h1 style="margin-top: 40px;">イベント新規作成</h1>
<%= render 'form', schedule: @schedule %>

<p><%= @attention %></p>
<p><%= @msg %></p>
<div style="clear: both; padding-top: 10px;"><%= link_to '日程一覧に戻る', root_path, { class: "btn-border" } %></div>

app/views/schedules/not_logged_in.html.erb
<p>ログイン情報が違います。再度ログインお願いします。</p>
<%= link_to "ログイン", login_path%>